# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('call_sign', models.CharField(max_length=10)),
                ('nfarl_member', models.BooleanField()),
                ('contact_me', models.BooleanField()),
                ('email', models.CharField(max_length=50)),
                ('first_time', models.BooleanField()),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
