# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='age',
        ),
        migrations.AddField(
            model_name='visitor',
            name='younger_than_18',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='call_sign',
            field=models.SlugField(max_length=10),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='first_time',
            field=models.BooleanField(default=False),
        ),
    ]
