# Generated by Django 2.0.6 on 2018-06-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_auto_20170529_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='call_sign',
            field=models.SlugField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
